UPDATE utils_occupation SET name = 'Broadcasting (Radio / Television)' WHERE id = 6;
UPDATE utils_occupation SET name = 'Fashion / Textile Art' WHERE id = 9;
UPDATE utils_occupation SET name = 'Film / Video / Television' WHERE id = 10;
UPDATE utils_occupation SET name = 'Fine Arts / Visual Arts / Graphic Design' WHERE id = 11;
UPDATE utils_occupation SET name = 'Theatrical Arts (Writing / Directing / Production)' WHERE id = 18;
UPDATE utils_occupation SET name = 'Entrepreneurship / Small Business Owner' WHERE id = 25;
UPDATE utils_occupation SET name = 'Arts Education / Therapy / Administration' WHERE id = 44;
UPDATE utils_occupation SET name = 'Museums / Libraries (Collections)' WHERE id = 50;
UPDATE utils_occupation SET name = 'Aerospace / Defense' WHERE id = 69;
UPDATE utils_occupation SET name = 'Lobbying / Labor Relations' WHERE id = 75;
UPDATE utils_occupation SET name = 'Military / Armed Forces and Defense' WHERE id = 77;
UPDATE utils_occupation SET name = 'Public Policy / Advocacy / Think Tanks' WHERE id = 80;
UPDATE utils_occupation SET name = 'Security / Intelligence (Federal)' WHERE id = 81;
UPDATE utils_occupation SET name = 'Alternative / Complementary Medicine' WHERE id = 83;
UPDATE utils_occupation SET name = 'Audiology & Speech Pathology / Communicative Disorders' WHERE id = 84;
UPDATE utils_occupation SET name = 'Recreation / Sports Medicine' WHERE id = 104;
UPDATE utils_occupation SET name = 'Animal Science / Zoology & Marine Science' WHERE id = 126;
UPDATE utils_occupation SET name = 'Bioinformatics / Biostatistics' WHERE id = 129;
UPDATE utils_occupation SET name = 'Biotechnology / Pharmaceuticals' WHERE id = 130;
UPDATE utils_occupation SET name = 'Botany / Forestry / Horticulture / Agriculture' WHERE id = 131;
UPDATE utils_occupation SET name = 'Chemistry / Chemical Engineering' WHERE id = 132;
UPDATE utils_occupation SET name = 'Genetics / Microbiology' WHERE id = 136;
UPDATE utils_occupation SET name = 'Library / Information Services' WHERE id = 138;
UPDATE utils_occupation SET name = 'Statistics / Mathematics' WHERE id = 144;
UPDATE utils_occupation SET name = 'Video / Computer Game Design' WHERE id = 158;
UPDATE utils_occupation SET name = 'Building / Grounds maintenance' WHERE id = 161;